[package]
name = "advent"
version = "0.1.0"
edition = "2021"

[lib]
name = "advent_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
csv = "1.3.1"
serde = { version = "1", features = ["derive"] }